### ISSUE TITLE
Inconsistent cash balance calculation

### ISSUE THREAD

**Issue by pvieira84** [VibeNL/GhostfolioSidekick#286]
In most of my accounts, I just have buy/sell transactions hence I personally don't have much interest in the cash balance feature. Any chance of introducing a setting which allows to disable the update of cash balance for a particular account?

This suggestion comes from me having some hard time understanding how cash balances are calculated with this tool.
Here's one adjusted example of one of my accounts:

> ActivityType,Symbol,Date,Currency,Quantity,UnitPrice,Fee
Buy,ABC,2024-05-14,EUR,5.4800,5.17,0
Buy,DEF,2024-05-14,EUR,0.64,23.05,0
Buy,GHI,2024-05-14,EUR,0.25,49.43,0
Buy,JKL,2024-05-14,EUR,1.69,20.53,0
Buy,MNO,2024-05-14,EUR,0.35,28.28,0
Sell,ABC,2024-07-02,EUR,5.4800,5.21,0
Sell,DEF,2024-07-02,EUR,0.64,22.95,0
Sell,GHI,2024-07-02,EUR,0.25,46.97,0
Sell,JKL,2024-07-02,EUR,1.69,20.63,0
Sell,MNO,2024-07-02,EUR,0.35,29.52,0

This generates the following cash balance in ghostfolio which does not seem correct to me:
<img width="373" alt="image" src="https://github.com/user-attachments/assets/240cdfdb-4f56-4b43-96e9-368437766743">

Thanks in advance

**Comment by VibeNL** [comment]
I'll have a look at it.

**Comment by VibeNL** [comment]
The problem seems to be that there are multiple identical dates. I updated the code to create a balance per day to avoid this issue. 

You can test is by installing the PR-version: docker pull vibenl/ghostfoliosidekick:pr-287

For the other comment, disabling balance could be a feature 👍 . Could you create another feature request to keep the issues seperate? Also I'm in the middle of a huge rewrite so non critical bugs are a bit of a low priority 👼

**Comment by pvieira84** [comment]
I've tested it and in math terms this seems correct now - I have created another issue to track the new feature in case you decide to implement it.

**Comment by VibeNL** [comment]
Good to hear 😄
