### ISSUE TITLE
Idea: Add workaround for staking rewards

### ISSUE THREAD

**Issue by VibeNL** [VibeNL/GhostfolioSidekick#64]
Currently Ghostfolio has no support for staking, lets implement a workaround:

- for every stake reward
  - create a dividend record the the currency amount 
  - create a buy order for exactly the same amount

**Comment by Joren-vanGoethem** [comment]
this would not be ideal, 
ghostfolio should imo soon implement either a default or a per-stock tax you can set so this gets deducted from your dividend so you know how much you really have left
this would break this kind of implementation since you can't really account for this in your code
we should instead open a PR on ghostfolio to fix this issue and add 'stake reward' as an option

**Comment by VibeNL** [comment]
I totally agree, however there have been multiple attempts to implement this (see https://github.com/ghostfolio/ghostfolio/pull/2145) and no real progress seems to be happening. 

However this was still an idea and can be investigated.
